
### signup
POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
    "username": "awarlock",
    "first_name": "Adam",
    "last_name": "Warlock",
    "password": "!2@1234"
}

### signin
POST http://localhost:3000/api/users/signin
Content-Type: application/json

{
    "username": "awarlock",
    "password": "!2@1234"
}

### get current user
GET http://localhost:3000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhd2FybG9jayIsImZpcnN0X25hbWUiOiJBZGFtIiwibGFzdF9uYW1lIjoiV2FybG9jayIsInBhc3N3b3JkIjpudWxsLCJpYXQiOjE2OTIzNTQzNzAsImV4cCI6MTY5NDk0NjM3MH0.4fy-piUnJwPO3QWcAJLS9M0bpGHjP3JjnjoTOhsOngY

### update current user
POST http://localhost:3000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhd2FybG9jayIsImZpcnN0X25hbWUiOiJBZGFtIiwibGFzdF9uYW1lIjoiV2FybG9jayIsInBhc3N3b3JkIjpudWxsLCJpYXQiOjE2OTIzNTQzNzAsImV4cCI6MTY5NDk0NjM3MH0.4fy-piUnJwPO3QWcAJLS9M0bpGHjP3JjnjoTOhsOngY

{
    "first_name": "Adam",
    "last_name": "Warlock"
}

###
GET http://localhost:3000/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjkyMjAwODc2LCJleHAiOjE2OTQ3OTI4NzZ9.h0UHMfXfuuC4716wZyzfS9CKImYLGFcrlw0nOqyywgc

###
GET http://localhost:3000/api/blogs/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjkyMjAwODc2LCJleHAiOjE2OTQ3OTI4NzZ9.h0UHMfXfuuC4716wZyzfS9CKImYLGFcrlw0nOqyywgc

###
POST http://localhost:3000/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjkyMjAwODc2LCJleHAiOjE2OTQ3OTI4NzZ9.h0UHMfXfuuC4716wZyzfS9CKImYLGFcrlw0nOqyywgc

{
    "title": "Test Title",
    "content": "Test Conent"
}

###
POST http://localhost:3000/api/blogs/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjkyMjAwODc2LCJleHAiOjE2OTQ3OTI4NzZ9.h0UHMfXfuuC4716wZyzfS9CKImYLGFcrlw0nOqyywgc

{
    "title": "Test Title 2",
    "content": "Test Conent 2"
}

###
DELETE http://localhost:3000/api/blogs/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjkyMjAwODc2LCJleHAiOjE2OTQ3OTI4NzZ9.h0UHMfXfuuC4716wZyzfS9CKImYLGFcrlw0nOqyywgc
